import { NextResponse } from 'next/server';
import type { NextRequest } from 'next/server';
import { getDocument, readDocumentFile } from '@/lib/store';
import { parseDocumentShareToken } from '@/lib/share';

/**
 * Public, login-free download of a shared document via a signed, expiring token.
 * The link is generated by "send to client" and delivered through n8n.
 */
export async function GET(_request: NextRequest, { params }: { params: Promise<{ token: string }> }) {
  const { token } = await params;
  const parsed = parseDocumentShareToken(token);
  if (!parsed) {
    return NextResponse.json({ ok: false, error: 'הקישור אינו תקין או שפג תוקפו' }, { status: 404 });
  }

  const record = getDocument(parsed.documentId);
  if (!record) return NextResponse.json({ ok: false, error: 'המסמך לא נמצא' }, { status: 404 });

  const file = readDocumentFile(record);
  if (!file) return NextResponse.json({ ok: false, error: 'הקובץ חסר' }, { status: 404 });

  const encodedName = encodeURIComponent(record.originalName);
  return new NextResponse(new Uint8Array(file), {
    headers: {
      'Content-Type': record.mimeType || 'application/octet-stream',
      'Content-Length': String(file.length),
      'Content-Disposition': `inline; filename*=UTF-8''${encodedName}`,
      'Cache-Control': 'private, no-store',
    },
  });
}
